# Generated by Django 4.0.5 on 2023-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0002_categoria_impuestos_proveedores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='idProveedores',
            new_name='idProveedor',
        ),
    ]
