# Generated by Django 4.0.5 on 2023-07-03 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0003_rename_idproveedores_productos_idproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('stockActual', models.IntegerField(verbose_name='Stock Actual')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.productos', unique=True, verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'al Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Detalle de Compra')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fechaPedido', models.DateField(verbose_name='Fecha de Pedido')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('fechaEnvio', models.DateField(verbose_name='Fecha de Envío')),
                ('idInventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym1.inventario', verbose_name='Inventario')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
