# Generated by Django 4.0.5 on 2023-07-03 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0004_inventario_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeduccion',
            fields=[
                ('idTipoDeduccion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDeduccion', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Tipo de Dduccion')),
                ('descripcionTipoDeduccion', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Descripcion')),
            ],
        ),
    ]
