# Generated by Django 4.0.5 on 2023-07-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0008_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionFisica',
            fields=[
                ('idInformacionFisica', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Informacion Fisica')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Altura')),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cintura')),
                ('pecho', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pecho')),
                ('brazo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Brazo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Informacion Fisica',
                'verbose_name_plural': 'Informacion Fisicas',
            },
        ),
    ]
