# Generated by Django 4.0.5 on 2023-07-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0010_tipomembresia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomembresia',
            options={'verbose_name': 'Tipo Membresia', 'verbose_name_plural': 'Tipo Membresias'},
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('idMembresia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fechaFinal', models.DateField(verbose_name='Fecha Final')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.cliente', verbose_name='Cliente')),
                ('idTipoMembresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.tipomembresia', verbose_name='Tipo Membresia')),
            ],
            options={
                'verbose_name': 'Membresia',
                'verbose_name_plural': 'Membresias',
            },
        ),
    ]
