# Generated by Django 4.0.5 on 2023-07-04 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0011_alter_tipomembresia_options_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecetaNutricional',
            fields=[
                ('idTipoRecetaNutricional', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoRecetaNutricional', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Nombre')),
                ('detalleTipoRecetaNutricional', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Tipo Receta Nutricional',
                'verbose_name_plural': 'Tipo Receta Nutricional',
            },
        ),
    ]
