# Generated by Django 4.0.5 on 2023-07-05 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0012_tiporecetanutricional'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaNutricional',
            fields=[
                ('idReceta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Ingredientes')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('idtipoRecetaNutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.tiporecetanutricional', verbose_name='Tipo Receta')),
            ],
            options={
                'verbose_name': 'Receta Nutricional',
                'verbose_name_plural': 'Receta Nutricional',
            },
        ),
    ]
