# Generated by Django 4.0.5 on 2023-07-05 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0013_recetanutricional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodeduccion',
            options={'verbose_name': 'Tipo Deduccion', 'verbose_name_plural': 'Tipo Deduccion'},
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('idPlanNutricional', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fechaFinal', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.cliente', verbose_name='Cliente')),
                ('idReceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.recetanutricional', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Plan Nutricional',
            },
        ),
    ]
