# Generated by Django 4.0.5 on 2023-07-05 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0014_alter_tipodeduccion_options_plannutricional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('idTipoMaquina', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoMaquina', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Nombre')),
                ('detalleTipoMaquina', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Tipo Maquina',
                'verbose_name_plural': 'Tipo Maquina',
            },
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='fechaFinal',
            field=models.DateField(blank=True, verbose_name='Fecha Final'),
        ),
    ]
