# Generated by Django 4.0.5 on 2023-07-06 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0015_tipomaquina_alter_plannutricional_fechafinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjerciciosRutina',
            fields=[
                ('idEjerciciosRutina', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEjercicio', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Nombre')),
                ('series', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Series')),
                ('repeticiones', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Repeticiones')),
                ('descanso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descanso')),
                ('idTipoMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.recetanutricional', verbose_name='Tipo Maquina')),
            ],
            options={
                'verbose_name': 'Ejercicios Rutina',
                'verbose_name_plural': 'Ejercicios Rutinas',
            },
        ),
    ]
