# Generated by Django 4.0.5 on 2023-07-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0016_ejerciciosrutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciosrutina',
            name='idTipoMaquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.tipomaquina', verbose_name='Tipo Maquina'),
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('idRutina', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fechaFinal', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.cliente', verbose_name='Cliente')),
                ('idEjerciciosRutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.ejerciciosrutina', verbose_name='Rutina')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
    ]
