# Generated by Django 4.0.5 on 2023-07-06 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0018_salon_alter_rutina_fechafinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('idClases', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreClases', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Clases')),
                ('detalleClases', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Detalle')),
                ('idSalon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Clases',
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
