# Generated by Django 4.0.5 on 2023-07-06 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0020_clasescliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('idPlanilla', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePlanilla', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Nombre')),
                ('fechaInicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fechaFinal', models.DateField(null=True, verbose_name='Fecha Final')),
                ('fechaPago', models.DateField(null=True, verbose_name='Fecha Final')),
                ('detallePlanilla', models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ áéíóúÁÉÍÓÚ ]*$', 'No puede ingresar números a este campo.'), django.core.validators.RegexValidator('^(?!.*(\\w)\\1{2,}).+$', 'No se pueden ingresar letras repetidas más de 2 veces')], verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
            },
        ),
    ]
