# Generated by Django 4.0.5 on 2023-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0022_tipobono_cargoempleado_bono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoempleado',
            name='fechaFinal',
            field=models.DateField(null=True, verbose_name='Fecha Final'),
        ),
    ]
